language: python
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - py.test tests/ -v --cov worker_images --cov-report term-missing
  - ls -la
  - ls -la tests/
  - ls -la worker_images
after_success:
  - coveralls