version: '3'
services:
  nats-streaming:
    image: nats-streaming
    ports:
     - "4222:4222"
    command: ["-cid", "serieall"]
  worker_images:
    build: .
    depends_on:
      - nats-streaming
    volumes:
      - /var/www:/var/www
